#!/usr/bin/perl

use strict;
use v5.8.4;
use warnings;
use lab4 qw (check);
use labcommon qw (analyze);

my $argc = $#ARGV + 1;

if($argc != 3) {
	print "Usage: $0 labnum labvar\n";
	exit;
}

print "labnum = $ARGV[0], labvar = $ARGV[1], project dir = $ARGV[2]\n";

if($ARGV[0] == 4) { 
	labcommon::analyze($ARGV[2]);
	lab4::check( $ARGV[1], $ARGV[2] );
} elsif($ARGV[0] == 5) { 
	print "Lab5 checker not implemented!\n";
} elsif($ARGV[0] == 6) { 
	print "Lab6 checker not implemented!\n";
} else {
	print "Unknown lab number\n";
}
